version: '3.8'
services:
  fastapi:
    build:
      context: .
    restart: always
    environment:
      - TZ=Asia/Seoul
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_URL=${DB_URL}
      - PROFILE=${PROFILE}
      - HOST=${HOST}
      - PORT=${PORT}
      - GATEWAY_URL=${GATEWAY_URL}
    container_name: notify-service
    ports:
      - ${PORT}:${PORT}